### ISSUE TITLE
Änderung der Sprache für Universität Gent von "Flämisch" auf "Niederländisch"

### ISSUE THREAD

**Issue by chrdrn** [faucommsci/erasmus-program#4]

**Comment by chrdrn** [comment]
@emmaleun Vielen Dank für die Info. Ich bin mir selbst nicht mehr sicher, warum ich dort "flämisch" angegeben habe. Kannst du bitte noch mal checken, in welcher Sprache die Kurse konkret angeboten werden (gerne auch mit Link zur Dokumentation)?

**Comment by emmaleun** [comment]
@chrdrn Klar, anbei sind zwei Links:
1.
[Study guide (ugent.be)](https://studiekiezer.ugent.be/en/zoek?zt=&aj=2024&otc=Ba&otc=ManaBa&otc=EXCH&ig=5391&voMa=&voPB=&voAB=)
Die allgemeine Kursübersicht für Exchange Studierende (BA und MA): Man kann nur zwischen englischen und niederländischen Kursen für exchange students wählen

2.
[How to apply as an exchange student? — For prospective students — Ghent University (ugent.be)](https://www.ugent.be/prospect/en/administration/application/application-exchange)
Bei den allgemeinen Anforderungen werden auch nur niederländisch und englisch bei "language skills" angeboten.

**Comment by chrdrn** [comment]
@emmaleun Super! Dann kümmere ich mich darum, dass die Daten der Tabelle geändert werden.
